# $ docker run --name some-redis -d redis

# Redis
# Nginx -> serving static frontend files
# Gunicorn (kan kanskje kjøre med "flask run", siden det bare er kontoret)
# rq workers ?
# 

version: "3.9"
services:
  frontend:
    build: ?
  web:
    build: backend.Dockerfile
    command: gunicorn -w 4 app:app --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env.prod # TODO
    networks:
      - nginx_network
  redis:
    image: "redis:alpine"
    networks:
      - nginx_network
  rq:
    build: rq.Dockerfile
    command: rq worker
  rq-dashboard:
    build: rq.Dockerfile
    command: rq-dashboard -H rq-server # ?
  nginx:
    image: "nginx:alpine"
    ports:
      - 80:80
    # volumes:
    #   - ./config/nginx/conf.d:/etc/nginx/conf.d
    #   - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
    #   - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume